# ============================================================
#  IIQ Console Plugin - Shared Build Properties
#  This file is committed to source control.
#  Do NOT put your personal paths here.
#  Put YOUR local iiq.home path in user.build.properties
# ============================================================

plugin.name=IIQConsolePlugin
plugin.version=1.0

src.dir=src
build.dir=build
classes.dir=${build.dir}/classes
dist.dir=${build.dir}/dist

# UI and config dirs
ui.dir=ui
import.dir=import
db.dir=db
