# ============================================================
#  IIQ Console Plugin - USER Build Properties
#  THIS FILE IS PERSONAL, do NOT commit to source control.
#  Add this filename to your .gitignore
#
#  Copy this file and set your own iiq.home path below.
# ============================================================

# Set this to YOUR local WEB-INF path
iiq.home=/Users/niharkalyanam/Desktop/Sailpoint-Files/Apache/apache-tomcat-9.0.43/webapps/identityiq/WEB-INF
